# Use `cron` or `at` option to specify that a job should run as scheduled once
# over all workers. The `every` option will run the job once per worker instance
# at the specified interval.


###########################
# PERIODIC JOBS ARE REPLACING SIDEKIQ SCHEDULER

# Please add new periodic jobs in sidekiq_periodic_jobs.yml

SidekiqAlive::CleanupQueues:
  cron: "*/30 * * * * America/New_York"
  class: SidekiqAlive::CleanupQueues
  description: "Cleanup Sidekiq Alive Zombie Queues"

VRE::CreateCh31SubmissionsReportJob:
  cron: "0 0 * * * America/New_York"
  include_metadata: true
  description: "Send a daily report to the VRE team about Chapter 31 submissions"

# EducationForm::Create10203ApplicantDecisionLetters:
#   cron: "45 4 * * MON-FRI America/New_York"
#   description: "Send 10203 applicant decision letters to applicants"
#   enabled: false

# Webhooks::SchedulerJob:
#   at: "<%=Settings.vba_documents.v2_enabled ? 0.seconds.from_now : 100.years.from_now%>"
#   description: Starts off webhook based notifications


